/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ybs_audiojnilib_JNISend */

#ifndef _Included_com_ybs_audiojnilib_JNISend
#define _Included_com_ybs_audiojnilib_JNISend


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ybs_audiojnilib_JNISend
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ybs_audiojnilib_AudioModule_getVersion
  (JNIEnv *env, jobject);

/*
 * Class:     com_ybs_audiojnilib_JNISend
 * Method:    run
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ybs_audiojnilib_AudioModule_run
  (JNIEnv *env, jobject obj);

/*
 * Class:     com_ybs_audiojnilib_JNISend
 * Method:    setVol
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ybs_audiojnilib_AudioModule_setVol
  (JNIEnv *env, jobject obj, jint vol);

#ifdef __cplusplus
}
#endif
#endif
