/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include <unistd.h>
#include "com_ybs_audiojnilib_AudioModule.h"
#include "android/log.h"

#include <sys/stat.h>
#include "ybsHalAlsa.h"

static const char *TAG="serial_port";
#define LOGI(fmt, args...) __android_log_print(ANDROID_LOG_INFO,  TAG, fmt, ##args)
#define LOGD(fmt, args...) __android_log_print(ANDROID_LOG_DEBUG, TAG, fmt, ##args)
#define LOGE(fmt, args...) __android_log_print(ANDROID_LOG_ERROR, TAG, fmt, ##args)



/* Header for class com_ybs_audiojnilib_JNITest */

/*
 * Class:     com_ybs_audiojnilib_JNISend
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ybs_audiojnilib_AudioModule_getVersion
        (JNIEnv *env, jobject){
    std::string hello = "V1.0.1";
    return env->NewStringUTF(hello.c_str());
}

/*
 * Class:     com_ybs_audiojnilib_JNISend
 * Method:    run
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ybs_audiojnilib_AudioModule_run
        (JNIEnv *env, jobject obj){
    system("su -c \"chmod 777 /dev/snd/pcmC0D0c\"");
    runAudio(env,obj);
    return 1;
}


/*
 * Class:     com_ybs_audiojnilib_JNISend
 * Method:    SetVol
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ybs_audiojnilib_AudioModule_setVol
        (JNIEnv *env, jobject obj, jint vol){

    return 1;
}


